### PR TITLE
feat: support serde serialisation and desalinisation

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by eivindbergem** [comment]
The commit looks fine, but I'm not sure what the use case for this is and I'm hesitant to bring in another dependency for a feature I don't see the point of. Why would you ever need this? If you need serialization, why wouldn't you just serialize the inner instance?

**Comment by aminya** [comment]
`AtomicOnceCell` is a generic container that can store data, and the ability for serialization and deserialization allows for easily using it in other structs that need to be serialized using a simple drive macro. The implementation I provided allows saving the data stored in `AtomicOnceCell` to the drive and loading it later. 

Most of the containers provide serde support through a feature (such as AtomicRefCell), and the std containers are supported by serde itself (e.g. `RwLock`, `Arc`, etc .). For example, here you see that Serde provides direct support for `RefCell` out of the box.
https://docs.rs/serde/1.0.183/src/serde/ser/impls.rs.html#593-606

**Comment by eivindbergem** [comment]
Ok, I guess we can add it. If you can fix the failing tests, I'll merge it in when all tests pass.

**Comment by aminya** [comment]
@eivindbergem Updated loom and added the changelog. It should fix the CI.

**Pull request merged**
